### ISSUE TITLE
Portal helper blocks tend to disappear when a portal is lit

### ISSUE THREAD

**Issue by muzikbike** [qouteall/ImmersivePortalsMod#1000]
This has been the case for a long time, but I did a quick search and found no reports on it. Not sure if intentional, but it's annoying.
![2022-02-28_12 10 19](https://user-images.githubusercontent.com/52297970/155981537-9c6b6604-671d-4ea6-9c94-95a9d96b8c95.png)
![2022-02-28_12 10 27](https://user-images.githubusercontent.com/52297970/155981540-ab1fd9b4-f908-4196-8f09-ca0c4e677b80.png)
.

**Comment by ImSpaceLover** [comment]
It is intentional because Portal helpers aren't supposed to be used as frame block. Because of the way portal helpers work, if you'd make another pair of portals with the same ratio, the portals would overlap with each other. Just break the portal helpers and place any other frame block that you want

**Comment by qouteall** [comment]
Yes it's intentional, it aims avoiding linking to a frame that already has portal entities
