### ISSUE TITLE
Incompatible with Universal Graves

### ISSUE THREAD

**Issue by luftwafflezz** [qouteall/ImmersivePortalsMod#1145]
### According to your testing, does the issue occur with ONLY Immersive Portals mod and Farbic API?

No

### Describe the issue

I added a bunch of new mods, and it caused a startup error. I added them back in one by one to troubleshoot and once I added Universal Graves, it got the error again.

### Post the log here

```shell
https://pastebin.com/QBP1JXvC
(it was too long to paste here)
```

**Comment by qouteall** [comment]
ImmPtl seems incompatible with polymer and universal graves contains polymer

**Comment by luftwafflezz** [comment]
Ah ok.

**Comment by Patbox** [comment]
Try updating polymer manually with https://github.com/Patbox/polymer/#download 

If issue persist please report it or polymer's repo

**Comment by luftwafflezz** [comment]
Ok, I’ll try this when I can.

**Comment by koelle25** [comment]
I can confirm that the issue is with Polymer.

I manually inserted the current version (0.2.9) in the mod-jar of the *Universal Graves* mod in `META-INF/jars/` (and deleted the old 0.2.2 version). Of course I also had to update the `fabric.mod.json` to reflect the new file name (`"file": "META-INF/jars/polymer-all-0.2.9+1.19.jar"` instead of `"file": "META-INF/jars/polymer-0.2.2+1.19.jar"`).

Afterwards, Minecraft starts without a problem when using both *Universal Graves* and *Immersive Portals*.

**Comment by luftwafflezz** [comment]
I’ll wait for the patch.

**Comment by Patbox** [comment]
Just install standalone polymer version. There is no real reason not to

**Comment by luftwafflezz** [comment]
So I just put the latest version of Polymer into the modpack and Universal Graves will use it automatically? I can’t do all the things that @koelle25 did because the CurseForge app will install the normal jar, not the modified one.

**Comment by Patbox** [comment]
Yep. Fabric automatically loads latest one

**Comment by luftwafflezz** [comment]
Ok, I’ll try it as soon as possible.

**Comment by luftwafflezz** [comment]
Gosh I totally forgot about this. In the latest versions it appears to be fixed though
