### ISSUE TITLE
Sodium 0.4.11 & Iris 1.6.2 compat

### ISSUE THREAD

**Issue by Lolothepro** [qouteall/ImmersivePortalsMod#1336]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.4

### Describe the issue

.

**Comment by SeymourGx** [comment]
Seconded. Kinda rough that Immersive Portals has the EXACT Sodium/Iris versions listed as a Required dependency, as opposed to either loosening up the range or making it Optional.

**Comment by Stanlyhalo** [comment]
Same, only time I got this to work, is via using 2.6.4, and a very specific version of sodium... but then I can't use another mod because now sodium is "outdated".

**Comment by qouteall** [comment]
@SeymourGx I have to clarify that being compatible with only one Sodium version **is not Immersive Portals' fault**. To make portal rendering work, ImmPtl must deeply change Sodium rendering process, and ImmPtl uses Sodium internal API which Sodium does not keep stable.

**Comment by qouteall** [comment]
And ImmPtl does not depend on Sodium. In nvidia videocard there is a driver bug that Sodium workarounds, which is also useful for ImmPtl. But on AMD and Intel videocard there is no such dependency.

**Comment by SeymourGx** [comment]
Understandable. To clarify, I just mean the fact that when one attempts to launch ImmPtl right now with the new Sodium/Iris, it'll give a mod dependency failure and refuse to launch, due to being a Required dependency. Makes sense given how immersive ImmPtl is with graphics. Maybe making a minimum version but no maximum?
I at least saw in Sodium's new patch that they're trying to add a stable API to stop this sort of thing. Perhaps this'll be moot in the near future.

**Comment by qouteall** [comment]
Resolved in 2.6.7
