### ISSUE TITLE
Crash upon loading world with the correct Sodium/Iris versions. (Unexpected error)

### ISSUE THREAD

**Issue by Axodique** [qouteall/ImmersivePortalsMod#1390]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.19.2

### Describe the issue

https://pastebin.com/pgYbE8Nx

**Comment by qouteall** [comment]
Seem to be a mod incompatibility issue. Similar crash happens in Forge version with custom camera entity mod. But this installation seems not having custom camera entity mod. 

The binary search is a way of finding the incompatible mod without removing the mods one-by-one.

The procedure is simple:
1. Backup the world because removing mod cause its content to be removed.
2. Remove half of the existing mods, and put them aside.
3. Run the game.
4. Does the issue still exist?
If YES: Repeat from step 2 with the current mods.
If NO: Swap out the current mods with the ones set aside, and repeat from step 1.
5. Repeat this process until the problematic mod/s have been found.

**Comment by Axodique** [comment]
Turns out it was continuity causing the crash, not immersive portals. I don't know why the crash report said it was immersive portals... the crash happens whether or not IP is loaded.
