### ISSUE TITLE
Entities disappear or are rendered in other chunks

### ISSUE THREAD

**Issue by rafamape10100** [qouteall/ImmersivePortalsMod#1392]
### Is it a mod compatibility issue?

Idk

### Minecraft version

1.19.2

### Describe the issue

Hello,
I've had problems with some of my 1.19.2 Fabric server portals as they caused entities from multiple chunks to render into one. In other words, they were rendered at the height at which they were, but all in the same chunks, this results in flying horses, golems, cats..., that cannot be hit because it is only something visual
In another place on the map where I created a portal, the villagers and all the entities of those chunks were also no longer visible, I don't know if it was this or that they rendered very far away and that is why they were not visible
I have Entity culling, More culling and Bobby installed, I don't know if this could be the reason
Client log:
[latest.log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12087837/latest.log)
Server log:
[latest (1).log](https://github.com/iPortalTeam/ImmersivePortalsMod/files/12087847/latest.1.log)

**Comment by qouteall** [comment]
There are many mods and it may be a mod compatibility issue.

The binary search is a way of finding the incompatible mod without removing the mods one-by-one.

The procedure is simple:
1. Backup the world because removing mod cause its content to be removed.
2. Remove half of the existing mods, and put them aside.
3. Run the game.
4. Does the issue still exist?
If YES: Repeat from step 2 with the current mods.
If NO: Swap out the current mods with the ones set aside, and repeat from step 1.
5. Repeat this process until the problematic mod/s have been found.

**Comment by qouteall** [comment]
Close because no reply.
