### ISSUE TITLE
Incompatible with Textile Backup

### ISSUE THREAD

**Issue by xMathayus** [qouteall/ImmersivePortalsMod#1402]
### Is it a mod compatibility issue?

Yes

### Minecraft version

1.20.1

### Describe the issue

The latest Aug 4 Update is no longer compatible with Textile Backup Mod.

**Comment by qouteall** [comment]
https://github.com/Szum123321/textile_backup

**Comment by qouteall** [comment]
The cause is that Textile Backup is doing non-thread-safe operations. ImmPtl's assertion is triggered in that non-thread-safe operation and cause the backup process to abort. This is primarily an issue of Textile Backup, but manifests when ImmPtl is installed. Even without ImmPtl, the non-thread-safe operation could cause rare bugs in Textile Backup (the change of bugs are very rare so it's usually unnoticed).

**Comment by qouteall** [comment]
In the latest version, the assertion has been changed to non-exception-throwing. So the issue does not manifest. But the thread safety of Textile Backup still exists.

**Comment by xMathayus** [comment]
Thank you. seems to be working again
