### ISSUE TITLE
More portal wand non-operator settings

### ISSUE THREAD

**Issue by FuzionCraft** [qouteall/ImmersivePortalsMod#1532]
### Suggestion

Currently there is no option to allow non-operator survival players to use the portal wand even if they have one.

This can be a problem if players are not an operator and are using the wand in creative mode but then change to survival to perform another task.
This also prevents players from using the portal wand to access the more indepth mechanics of the mod if they are in survival. (given that the portal wand is not craftable this situation would only arise if the player has decided to start with the portal wand or has some other addition to make it obtainable)

The best way I could think of for fixing this issue would be to add another config option or gamerule to allow all players to use the portal wand, or a config option to change the permission level needed to use it.

**Comment by qouteall** [comment]
In the latest version of this mod (in MC 1.20.4) there exists an option `portalWandUsableOnSurvivalMode`. If enabled, survival mode player can use portal wand. Effective on server side.

The portal wand is originally designed for creative mode. It's too powerful for normal survival (the player can easily create tons of big portals using portal wand).

I am considering making nether portal mode default to `adaptive` so that survival mode player can make portals with rotation and scaling in a balanced manner.

**Comment by FuzionCraft** [comment]
Oh. didn't realsies that was in the newest version. I was using 1.20.1
