### ISSUE TITLE
Incompatible with Adorn's seat

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#327]

**Comment by copygirl** [comment]
As I also pointed out in the linked issue, this problem might be worth prioritizing because people with photosensitive epilepsy can be affected. When turning the camera horizontally before sitting down in an Adorn seat, it causes the camera to shake / jitter heavily.

My friends also say there might be a similar issue with boats where the camera continuously turns, so it could be an issue with other rideable entities as well?

**Comment by qouteall** [comment]
Close because outdated.
