### ISSUE TITLE
Can't play online

### ISSUE THREAD

**Issue by raulib** [qouteall/ImmersivePortalsMod#37]
![fuk u](https://user-images.githubusercontent.com/44544183/68072294-888d9000-fd84-11e9-89fc-0b57c187bbce.png)

This happens when i join online. I want this to be on online since it would give a real advantage to the game

**Comment by qouteall** [comment]
Which server are you joining? This mod is not compatible with some server plugins. What other mods do you install?

**Comment by qouteall** [comment]
The server have to install immersive portals mod if you want to play online. If the server does not install this mod, you have to uninstall this mod to join that server.

**Comment by raulib** [comment]
Any shitty generic server. 
Also that's sad

**Comment by doncullen** [comment]
No need to get hostile.  He's doing free dev work on the mod, it's not like you're paying him.  The least you could do is be understanding, appreciative, and most of all, supportive.  

@qouteall  - don't take what he said personally.  Internet's full of those people, unfortunately.  Rest assured, your efforts are most definitely appreciated.  

I came here because I experienced the same issue and was going to report it, but I see it's been reported previously.  Let me know if there's anything I can do to help you figure this out.  

On a side note; you mentioned installing the mod server-side.  I'm willing to do that; what would your recommendation be if the server I'm running is a Paper server (papermc.io)?  Would I also need to configure the server to support fabric?  Additionally; what happens if players without the mod connects to the server running the mod?  Would they be prevented from connecting?

**Comment by qouteall** [comment]
This mod probably won't be compatible with some server plugins as this mod hacks into chunk loading ,dimension managing and syncing mechanics. If a player without this mod logins to a server with this mod the game may crash or the player will not see any blocks.

**Comment by doncullen** [comment]
Understood, so servers would need to make it clear that the mod is required for gameplay, that vanilla gameplay is not an option. Thank you for the clarification.
