### ISSUE TITLE
[Suggestion] Split the mod into several parts

### ISSUE THREAD

**Issue by Leo40Git** [qouteall/ImmersivePortalsMod#371]
This was already mentioned in #216, but I figured I'd bring it back since that issue has gotten somewhat buried.
* **Immersive Portals API:** Smooth teleportation handling and camera magic
* **Immersive Portals:** Applying the API to Nether & End Portals, and the "alternate dimension" stuff
* **Extended Reach:** This has nothing to do with Immersive Portals, and so should probably be split into a separate mod

**Comment by qouteall** [comment]
It's being considered.

**Comment by qouteall** [comment]
I am going to remove the hand reach potion thing. And the extended reach in creative is already disabled by default.

**Comment by qouteall** [comment]
And splitting requires small changes to my remapper. My current plan is to split the fabric version but the forge version is not split.

**Comment by Jarfeh** [comment]
When you say you're going to remove the hand reach, do you mean reaching through portals?

**Comment by Leo40Git** [comment]
No @Jarfeh, he's referring to being able to extend the range of blocks you can reach/interact with.

**Comment by Ynaught** [comment]
I personally wish for dimension stacking to be separate as well as the alternate dimensions. The "immersive" part tends to cause me to crash alot and IDK why. I don't even care for that. I don't mind teleporting, I just want to be able to progress by digging down.

Whats weird about my current crashes is it only happens if I enable the alternate dimensions. . . idk why that would be though.
That's why I want to remove the immersive part, because I atleast want to test if the overworld won't crash and it's an issue of loading that that dimension at the same time or something.

**Comment by qouteall** [comment]
@Ynaught post the crash report. If you use optifine, try switching to sodium
nevermind
