### ISSUE TITLE
Game Crashes When I Load Into A World with Optifine

### ISSUE THREAD

**Issue by TheTimeCraft** [qouteall/ImmersivePortalsMod#430]
When I Use OptiFine 1.16.2 HD U G3 with immersive portals 0.32 1.16.2 fabric it crashes when I load a world.

Error Code:
Error: java.lang.NullPointerException: Unexpected error
Exit Code: -1

I use it with these mods:
VoxelMap Fabric 1.16.2
Optifabric 1.5.0
OptiFine 1.16.2 HD U G3
Fabric API 0.20.1 Build 401
Replay Mod 1.16.2
Immersive Portals 0.32 fabric

**Comment by qouteall** [comment]
1.16.2 is not supported now it's recommended to use 1.16.3

**Comment by DavidChen-cxl** [comment]
> When I Use OptiFine 1.16.2 HD U G3 with immersive portals 0.32 1.16.2 fabric it crashes when I load a world.
> 
> Error Code:
> Error: java.lang.NullPointerException: Unexpected error
> Exit Code: -1
> 
> I use it with these mods:
> VoxelMap Fabric 1.16.2
> Optifabric 1.5.0
> OptiFine 1.16.2 HD U G3
> Fabric API 0.20.1 Build 401
> Replay Mod 1.16.2
> Immersive Portals 0.32 fabric

Sorry for replying under a closed issue... but would you please share how you managed to get it to work with the replay mod? It seems that replay mod won't render the surroundings on the other side of the portal, so i would lose the "see-through" feature after i render the path. 

Not sure if there is a solution or where to report the issue, since this may be immersive portals not communicating "the other dimension" to replay mod, or replay mod not reading the world on the other side correctly. I will make an issue if necessary.
