### ISSUE TITLE
pehkui not working

### ISSUE THREAD

**Issue by Oreo1184** [qouteall/ImmersivePortalsMod#588]
I have been trying to get the pehkui mod to work with this but everything I seem to try does not work, and I'm unable to find a guide to help, anytime I create 2 portal frames of different sizes using the portal helper block, once I light one of them it just creates an entire new portal the same size as the one that was lit, not affecting the different sized portal at all.

**Comment by Oreo1184** [comment]
also a quick note, I'm using the most recent version of both immersive portals and pehkui, 1.16.5

**Comment by Oreo1184** [comment]
I guess it's not much of a pehkui issue but more of an issue with different sized portals not linking with each other.

**Comment by SpacePogam** [comment]
You need to make sure the portals keep the same aspect ratio in size. EG - height 2, width 1 and another portal that is height 6, width 3.

**Comment by Firesgone** [comment]
I have this same issue. The mods work properly, but linking portals with the same aspect ratio is impossible currently.
The game would rather make a new portal than link to a different scale.

**Comment by ImSpaceLover** [comment]
Can you show a screenshot of your portals that aren't linking? Anytime I make the portals with different scale they're connecting properly. The problem may be on your side.

> I have this same issue. The mods work properly, but linking portals with the same aspect ratio is impossible currently.
> The game would rather make a new portal than link to a different scale.

**Comment by qouteall** [comment]
@Firesgone Do you get this issue with portal helper or nether portal?

**Comment by Firesgone** [comment]
@ImSpaceLover Here you go. I'm copy-pasting at the bottom.
@qouteall Nether Portal, the entire reason we even have Pehkui is because Immersive Portals works with it according to mod reviews.

I should elaborate, this is a server I'm playing on. We have Phosphor, Lithium, Origins, Immersive Portals & Pehkui. We just recently added Pehkui after finding out about this feature, no one has been able to get it to work so the owner left finding out to me since he's busy irl. I was able to find that other people are having this same problem despite us using the newest version of Immersive Portals and Pehkui. Pehkui only has one version for 1.16.5 so I came here since I know Immersive Portals has been frequently updated and the non-interaction between the mods would be on the Immersive Portals side. 

I tested the mod on both the server and in singleplayer for the same results. We didn't have reason to believe that we wouldn't be able to link with regular Nether Portals.

*Edit: I forgot to mention that all mods are working normally, with the exception that Immersive Portals and Pehkui are not interacting.

![image](https://user-images.githubusercontent.com/79805825/109453470-05775b00-7a07-11eb-887c-065a8524f4ac.png)
![image](https://user-images.githubusercontent.com/79805825/109453510-1cb64880-7a07-11eb-8773-5fd6d3193b66.png)
![image](https://user-images.githubusercontent.com/79805825/109453525-2a6bce00-7a07-11eb-9dac-61dce87b7453.png)
![image](https://user-images.githubusercontent.com/79805825/109453534-30fa4580-7a07-11eb-949a-f3717ac89823.png)

**Comment by VexianEmpire** [comment]
it does not work with obsidian only portalhelpers

**Comment by VexianEmpire** [comment]
nvm

**Comment by VexianEmpire** [comment]
in the config there is a portal option setting i forgot what it's called but you can find it on the wiki i gtg

**Comment by qouteall** [comment]
Change the nether portal mode to adaptive https://qouteall.fun/immptl/wiki/Portals#mode--adaptive

**Comment by Firesgone** [comment]
Oh! So this is a setting that has to be enabled in the config file.
Thanks for the update!

**Comment by InocentVictim** [comment]
HOW DO YOU GET PORTAL HELPER

**Comment by Razboy20** [comment]
@InocentVictim It is either in your creative inventory under misc, or just use the /give command...

Also, posting on an old comment thread asking for simple information that can be found on the wiki is not the correct way to go about it. 

Wiki: https://qouteall.fun/immptl/wiki
