### ISSUE TITLE
Incompatibility with Physics mod

### ISSUE THREAD

**Issue by CalaMariGold** [qouteall/ImmersivePortalsMod#658]
* Only the latest version is being supported. If you are using an outdated version, upgrade to the latest version.
* If you find an issue, check whether this issue happens with only this mod. If not, check which mod it's incompatible with. And include that mod's link in the issue.
* The Forge version is not being supported. If you find an issue of the Forge version, check whether the same issue exists for the Fabric version. Forge-version-specific issues belong to  https://github.com/qouteall/ImmersivePortalsModForForge/issues

https://www.curseforge.com/minecraft/mc-mods/physics-mod/files

When entering a world, the player's hand doesn't appear and you can't move at all.  This only occurs when entity physics are enabled in the Physics mod.

Not sure if this can be fixed on Immersive Portal's side, but Physics doesn't have any way to report issues it seems.

**Comment by qouteall** [comment]
PhysicsMod is not open source (I didn't find it. if you find tell me) so this cannot be solved on IP's side.

**Comment by joshcangit** [comment]
So far, I've used both mods in **1.17**.
- Immersive Portals 0.20
- Physics version 2.4.6

When the Nether portal is active, the **Physics** mod loses its visual effects only in the Nether. It returns back to normal after destroying the portal or setting `netherPortalMode` value to vanilla.

Maybe it's because they're seem to be fighting over the memory or CPU resource. I'm not sure if it's a compatibility issue since I was using both of them together.
