### ISSUE TITLE
Gravity Changer Compat

### ISSUE THREAD

**Issue by ParasiticSquid** [qouteall/ImmersivePortalsMod#877]
Basically compatibility for this:
https://www.curseforge.com/minecraft/mc-mods/gravitychanger

Reasoning being currently in the mod rotated portals, especially flipped world portals, don't effect player gravity. Flipped world portals sometimes stick the player in a short teleport loop half the time due to both sides trying to send the player through and not knowing which ground they should fall towards before they touch the other portal entrance. Another main thing is the possibility to use flipped portals to create the illusion that players or entities who enter the portal have just entered a upside down world similar to how gravitycraft back in the day did it by sticking other dimensions above or below a world either upside down or simply to extend world height seemlessly( but also laggy ).

No clue how likely this is but would be pretty neat and allow players who previously played the mod to relive the good old gravitycraft days and all the weird or bizarre builds

**Comment by Ch1216** [comment]
I would like to suggest a portal command stick that make all connected portals be able to change gravity, or if its not possible a portal command stick with just "/portal set_portal_nbt {teleportChangesGravity:true}" like how there are certain portal sticks when pehkui is added
also would like to add that this works in 1.18.1 (since gravity changer updated)

**Comment by ImSpaceLover** [comment]
You can make such command stick yourself with /portal debug create_command_stick "command"

**Comment by qouteall** [comment]
@Ch1216 I am considering this
