### ISSUE TITLE
Dimension Stack broken/functioning incorrectly with Amplified Nether mod installed?

### ISSUE THREAD

**Issue by SomeSpicyCheese** [qouteall/ImmersivePortalsMod#918]
My guess as to why is that the Nether's ceiling height is fixed at 128 in the code, and so because the Amplified Nether mod changes the ceiling height of the Nether, the Immersive Portals mod does not recognize that change and so still acts as if the bedrock ceiling of the Nether is at 128.
Is there any way of manually changing the height of the ceiling global portal in the Nether, or would that have to be fixed on the programming end of things?

**Comment by qouteall** [comment]
No, you are wrong, this mod's dimension stack y level is not fixed in 128 at all. This mod gets height by the dimension's `logical_height`. Amplified nether mod does not actually change the logical height of the dimension type. 
**It's Amplified Nether's issue.**
There is also a datapack called Amplified nether which does not change the logical height either.
This mod's latest version in 1.18.1 already supports customizing the Y level of dimension stack. (By clicking "Edit" in the dimension stack GUI)
