### ISSUE TITLE
Incompatible with Chisels&Bits

### ISSUE THREAD

**Issue by qouteall** [qouteall/ImmersivePortalsMod#963]
chiseling causes the block to appear invisible

**Comment by KMorris29** [comment]
I think you have two (very similar) mods confused. Bits&Chisels, the unofficial fabric port of Chisels&Bits, works fine with ImmPtl on my end.
While I have not tested it, I think the problem is with Chisels&Bits For Fabric, the OFFICIAL fabric port, which is still having some issues as it is rather new.
For example, I see this issue on Chisels&Bits github: https://github.com/ChiselsAndBits/Chisels-and-Bits/issues/873
They use the same issues page for forge and fabric versions, but that particular issue is for fabric with ImmPtl installed.

Ideally you should replace the warning against Bits&Chisels that shows up with a warning against Chisels&Bits For Fabric
(I had to check 3 times to make sure I got those names in the right order)

**Comment by marchermans** [comment]
It should compatible now.
I fixed a bug, if not hit me up on my discord I will see what I can do, allthough if you render a world normally it should not really matter I think.
